### ISSUE TITLE
Serious bug with click method

### ISSUE THREAD

**Issue by AndriusCTR** [TheGP/Imposter#1]
When using click method, if the element isDisabled, it will go into infinite recursive loop trying to wait for the element to become enabled. And if it never gets enabled, the timeout should stop this infinite waiting. But it does not.

element is in the view
waiting for el to become enabled
click button[name="confirm"] null
waitRandom 1.179426534625375
tryTranslate button[name="confirm"]
findElementAnywhere button[name="confirm"] null
element found: page CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
} {"_isDragging":false,"_timeoutSettings":{}}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}

element is in the view
waiting for el to become enabled
click button[name="confirm"] null
waitRandom 1.1938071642751942
tryTranslate button[name="confirm"]
findElementAnywhere button[name="confirm"] null
element found: page CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
} {"_isDragging":false,"_timeoutSettings":{}}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}

element is in the view
waiting for el to become enabled
click button[name="confirm"] null
waitRandom 0.24605512212723962
tryTranslate button[name="confirm"]
findElementAnywhere button[name="confirm"] null
element found: page CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
} {"_isDragging":false,"_timeoutSettings":{}}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}
isElementInView CdpElementHandle {
  handle: CdpJSHandle {},
  [Symbol(_isElementHandle)]: true
}

And so on

**Comment by TheGP** [comment]
Hmm why do u want to click on disabled element
Otherwise, you may pass timeout to that loop and break it after timeout is finished, and pull it to me haha

**Comment by AndriusCTR** [comment]
> Hmm why do u want to click on disabled element Otherwise, you may pass timeout to that loop and break it after timeout is finished, and pull it to me haha

Timeout does not work. The 'number 10' is the default timeout (whatever that means, seconds, minutes, hours?) and it still keeps looping indefinitely. The infinite loop and 'stuck' situation is not a feature. There must always be an exit. Throw exception or whatever.

**Comment by TheGP** [comment]
It doesnt work because u didnt fix it and pulled here ;) For me this bug doesn't matter.

**Comment by AndriusCTR** [comment]
> It doesnt work because u didnt fix it and pulled here ;) For me this bug doesn't matter.

I thought this was your project. Man, you are 'smart'.

**Comment by TheGP** [comment]
Pay me money then.

**Comment by AndriusCTR** [comment]
> Pay me money then.

Yes, indeed, you are very 'smart'.

Who paid you to make this package public?

I fixed it myself in my code, I don't need your fix for me. Maybe you are interested in fixing your buggy public code. If not - all ok, couldn't care less. I already wasted my time finding bugs for you, not going to do more

**Comment by TheGP** [comment]
Then fuck off if u cant fix it urself and do pull don't waste my time.
